global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:15692"]
    scrape_interval: 15s
    scrape_timeout: 4s

  - job_name: "mychat-webapp"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["localhost:3000"]
    scrape_interval: 5s
    scrape_timeout: 4s
